version: "3.8"
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "7000:7000"
    volumes:
      - ./client:/app
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:7001

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "7001:7001"
    volumes:
      - ./server:/app