version: "3.8"
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "7000:7000"
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "7001:7001"
